name: "🐛 Report a bug"
description: "Is something not working as you expect?"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a bug report.
  - type: textarea
    id: reproduce-bug
    attributes:
      label: "What steps are needed to reproduce the bug?"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "What did you expect to happen?"
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: "What actually happened?"
      description: "For example, what warnings or errors did you get?"
    validations:
      required: true
