name: node-ci

on: [push]

env:
  CI: true

jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [8, 10, 12]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install latest npm
        run: npm install --global npm@latest

      - name: npm install
        run: |
          npm install

      # Windows environment currently has random case drive letter
      # that Actions created.
      # See more: https://github.com/stylelint/stylelint/issues/4337
      - name: Test and Lint (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd ..
          cd D:\a\stylelint-scales\stylelint-scales
          npm test -- --ci
      - name: Lint and Test (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          npm run lint
          npm test -- --ci
